allowBuilds:
  '@apollo/protobufjs': set this to true or false
  '@firebase/util': set this to true or false
  '@scarf/scarf': set this to true or false
  '@sentry-internal/node-cpu-profiler': set this to true or false
  msgpackr-extract: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
